## Colors configuration
colors:
  # Default colors
  primary:
    background: '{BACKGROUND}'
    foreground: '{FOREGROUND}'
  # Normal colors
  normal:
    black:   '{BLACK}'
    red:     '{RED}'
    green:   '{GREEN}'
    yellow:  '{YELLOW}'
    blue:    '{BLUE}'
    magenta: '{MAGENTA}'
    cyan:    '{CYAN}'
    white:   '{WHITE}'
  # Bright colors
  bright:
    black:   '{ALTBLACK}'
    red:     '{ALTRED}'
    green:   '{ALTGREEN}'
    yellow:  '{ALTYELLOW}'
    blue:    '{ALTBLUE}'
    magenta: '{ALTMAGENTA}'
    cyan:    '{ALTCYAN}'
    white:   '{ALTWHITE}'